spring:
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: mykeyspace
      shcema-name: create_if_not_exists
      entity-base-package: beans.candidate.candidate.entity